# Generated by Django 2.1 on 2019-08-05 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_test', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
    ]
